import { useState } from "react";
import { Loader2, Sparkles, Wand2, X } from "lucide-react";
import { toast } from "sonner";

import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { api } from "@/lib/api";
import type { InvoiceForm } from "./invoice/InvoiceEditor";

interface AiInvoiceDialogProps {
  isOpen: boolean;
  onClose: () => void;
  onApply: (suggestions: Partial<InvoiceForm>) => void;
}

interface AiAssistResponse {
  suggestions: Partial<InvoiceForm>;
  meta: {
    followUpMessage: string;
    qualityChecklist: string[];
  };
}

const examplePrompts = [
  "Create an invoice for ABC Pvt Ltd for website development worth ₹50,000 with 18% GST.",
  "Invoice for John Doe for logo design & brand identity services, worth $1,200 due next week.",
  "Bill Client Corp for monthly IT consulting services at $5,000 with 10% discount.",
];

export function AiInvoiceDialog({ isOpen, onClose, onApply }: AiInvoiceDialogProps) {
  const [prompt, setPrompt] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleGenerate = async () => {
    if (!prompt.trim()) return;
    setIsLoading(true);
    setError(null);
    try {
      const res = await api.post<AiAssistResponse>("/ai/invoice-assist", { prompt });

      if (!res.success) {
        throw new Error(res.error.message ?? "Failed to get suggestions.");
      }

      if (res.data.suggestions) {
        onApply(res.data.suggestions);
        toast.success("Invoice Generated by AI!", {
          description: "All client details, items, rates & tax settings have been populated.",
        });
      } else {
        throw new Error("Failed to get suggestions.");
      }
    } catch (err) {
      const errorMessage = err instanceof Error ? err.message : "An unknown error occurred.";
      setError(errorMessage);
      toast.error("Failed to Generate Invoice", {
        description: errorMessage,
      });
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="w-[92vw] sm:max-w-xl rounded-3xl p-6 border border-border/80 bg-card/98 backdrop-blur-2xl shadow-2xl overflow-hidden animate-in fade-in-50 zoom-in-95 duration-200">
        <DialogHeader className="space-y-1.5 pb-3 border-b border-border/60 pr-4">
          <div className="flex items-center gap-2.5">
            <div className="h-8 w-8 rounded-full bg-primary/10 border border-primary/20 flex items-center justify-center text-primary shrink-0">
              <Sparkles className="h-4 w-4" />
            </div>
            <DialogTitle className="font-headline font-extrabold text-lg md:text-xl text-foreground">
              AI Invoice Assistant
            </DialogTitle>
          </div>
          <DialogDescription className="text-xs text-muted-foreground pt-1 leading-relaxed">
            Describe the invoice in plain language. AI will populate client, item & tax details automatically.
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-4 py-3">
          {/* Prompt Textarea */}
          <div className="relative">
            <textarea
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
              placeholder="e.g., Bill Client Corp for monthly consulting, $5000..."
              rows={3}
              className="w-full rounded-2xl border border-border/80 bg-card/60 p-3.5 text-xs text-foreground placeholder:text-muted-foreground outline-none resize-none font-sans focus:border-primary focus:ring-2 focus:ring-primary/20 transition-all shadow-sm leading-relaxed"
            />
            {prompt && (
              <button
                type="button"
                onClick={() => setPrompt("")}
                className="absolute top-3 right-3 p-1 rounded-full text-muted-foreground hover:text-foreground hover:bg-muted/80 transition-colors"
                title="Clear text"
              >
                <X className="h-3.5 w-3.5" />
              </button>
            )}
          </div>

          {/* Example Prompts List */}
          <div className="space-y-2">
            <span className="text-[11px] font-bold uppercase tracking-wider text-muted-foreground block">
              Examples:
            </span>
            <div className="space-y-2">
              {examplePrompts.map((p, idx) => (
                <button
                  key={idx}
                  type="button"
                  onClick={() => setPrompt(p)}
                  className={`w-full text-left px-4 py-2.5 rounded-2xl border text-xs transition-all cursor-pointer leading-relaxed ${
                    prompt === p
                      ? "border-primary bg-primary/10 text-primary font-bold shadow-sm"
                      : "border-border/60 bg-muted/30 text-foreground hover:bg-muted/70 hover:border-border"
                  }`}
                >
                  {p}
                </button>
              ))}
            </div>
          </div>

          {error && (
            <div className="p-3 rounded-2xl bg-destructive/10 border border-destructive/20 text-xs font-medium text-destructive">
              {error}
            </div>
          )}
        </div>

        <DialogFooter className="pt-3 border-t border-border/60 flex items-center justify-between sm:justify-end gap-3">
          <Button
            type="button"
            variant="outline"
            onClick={onClose}
            className="rounded-full h-10 px-5 text-xs font-bold"
          >
            Cancel
          </Button>
          <Button
            onClick={handleGenerate}
            disabled={isLoading || !prompt.trim()}
            className="rounded-full h-10 px-6 text-xs font-bold bg-primary text-primary-foreground hover:bg-primary/90 transition-all gap-1.5 shadow-md"
          >
            {isLoading ? (
              <>
                <Loader2 className="h-3.5 w-3.5 animate-spin" />
                <span>Generating...</span>
              </>
            ) : (
              <>
                <Wand2 className="h-3.5 w-3.5" />
                <span>Generate</span>
              </>
            )}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
