export type ThemeName = "light" | "dark" | "purple";

export const themes: Record<ThemeName, Record<string, string>> = {
  light: {
    surface: "#faf8ff",
    "surface-dim": "#d9d9e5",
    "surface-bright": "#faf8ff",
    "surface-container-lowest": "#ffffff",
    "surface-container-low": "#f3f3fe",
    "surface-container": "#ededf9",
    "surface-container-high": "#e7e7f3",
    "surface-container-highest": "#e1e2ed",
    "on-surface": "#191b23",
    "on-surface-variant": "#434655",
    "inverse-surface": "#2e3039",
    "inverse-on-surface": "#f0f0fb",
    outline: "#737686",
    "outline-variant": "#c3c6d7",
    "surface-tint": "#0053db",
    primary: "#004ac6",
    "on-primary": "#ffffff",
    "primary-container": "#2563eb",
    "on-primary-container": "#eeefff",
    "inverse-primary": "#b4c5ff",
    secondary: "#0060ac",
    "on-secondary": "#ffffff",
    "secondary-container": "#64a8fe",
    "on-secondary-container": "#003c70",
    tertiary: "#943700",
    "on-tertiary": "#ffffff",
    "tertiary-container": "#bc4800",
    "on-tertiary-container": "#ffede6",
    error: "#ba1a1a",
    "on-error": "#ffffff",
    "error-container": "#ffdad6",
    "on-error-container": "#93000a",
    "primary-fixed": "#dbe1ff",
    "primary-fixed-dim": "#b4c5ff",
    "on-primary-fixed": "#00174b",
    "on-primary-fixed-variant": "#003ea8",
    "secondary-fixed": "#d4e3ff",
    "secondary-fixed-dim": "#a4c9ff",
    "on-secondary-fixed": "#001c39",
    "on-secondary-fixed-variant": "#004883",
    "tertiary-fixed": "#ffdbcd",
    "tertiary-fixed-dim": "#ffb596",
    "on-tertiary-fixed": "#360f00",
    "on-tertiary-fixed-variant": "#7d2d00",
    background: "#faf8ff",
    "on-background": "#191b23",
    "surface-variant": "#e1e2ed",
    foreground: "#191b23",
    card: "#ffffff",
    "card-foreground": "#191b23",
    popover: "#ffffff",
    "popover-foreground": "#191b23",
    "primary-hover": "#003ea8",
    "primary-light": "#dbe1ff",
    muted: "#f3f3fe",
    "muted-foreground": "#434655",
    accent: "#f3f3fe",
    "accent-foreground": "#191b23",
    destructive: "#ba1a1a",
    "destructive-foreground": "#ffffff",
    success: "#22c55e",
    "success-foreground": "#ffffff",
    warning: "#f59e0b",
    "warning-foreground": "#ffffff",
    info: "#0060ac",
    "info-foreground": "#ffffff",
    purple: "#7c3aed",
    border: "#c3c6d7",
    input: "#c3c6d7",
    ring: "#004ac6",
    "chart-1": "#004ac6",
    "chart-2": "#0060ac",
    "chart-3": "#943700",
    "chart-4": "#2563eb",
    "chart-5": "#ba1a1a",
    sidebar: "#ffffff",
    "sidebar-foreground": "#191b23",
    "sidebar-primary": "#004ac6",
    "sidebar-primary-foreground": "#ffffff",
    "sidebar-accent": "#f3f3fe",
    "sidebar-accent-foreground": "#191b23",
    "sidebar-border": "#c3c6d7",
    "sidebar-ring": "#004ac6",
  },
  dark: {
    surface: "#0f172a",
    "surface-dim": "#020617",
    "surface-bright": "#1e293b",
    "surface-container-lowest": "#020617",
    "surface-container-low": "#0f172a",
    "surface-container": "#111827",
    "surface-container-high": "#1e293b",
    "surface-container-highest": "#334155",
    "on-surface": "#f8fafc",
    "on-surface-variant": "#cbd5e1",
    "inverse-surface": "#f8fafc",
    "inverse-on-surface": "#020617",
    outline: "#94a3b8",
    "outline-variant": "#334155",
    "surface-tint": "#2563eb",
    primary: "#3b82f6",
    "on-primary": "#ffffff",
    "primary-container": "#2563eb",
    "on-primary-container": "#ffffff",
    "inverse-primary": "#004ac6",
    secondary: "#64a8fe",
    "on-secondary": "#000000",
    "secondary-container": "#1e293b",
    "on-secondary-container": "#d4e3ff",
    tertiary: "#ffb596",
    "on-tertiary": "#000000",
    "tertiary-container": "#bc4800",
    "on-tertiary-container": "#ffede6",
    error: "#ef4444",
    "on-error": "#ffffff",
    "error-container": "#450a0a",
    "on-error-container": "#fecaca",
    "primary-fixed": "#dbe1ff",
    "primary-fixed-dim": "#b4c5ff",
    "on-primary-fixed": "#00174b",
    "on-primary-fixed-variant": "#2563eb",
    "secondary-fixed": "#d4e3ff",
    "secondary-fixed-dim": "#a4c9ff",
    "on-secondary-fixed": "#001c39",
    "on-secondary-fixed-variant": "#004883",
    "tertiary-fixed": "#ffdbcd",
    "tertiary-fixed-dim": "#ffb596",
    "on-tertiary-fixed": "#360f00",
    "on-tertiary-fixed-variant": "#7d2d00",
    background: "#020617",
    "on-background": "#f8fafc",
    "surface-variant": "#1e293b",
    foreground: "#f8fafc",
    card: "rgba(30, 41, 59, 0.7)",
    "card-foreground": "#f8fafc",
    popover: "#0f172a",
    "popover-foreground": "#f8fafc",
    "primary-hover": "#2563eb",
    "primary-light": "#1e3a8a",
    muted: "#0f172a",
    "muted-foreground": "#94a3b8",
    accent: "#1e293b",
    "accent-foreground": "#f8fafc",
    destructive: "#ef4444",
    "destructive-foreground": "#ffffff",
    success: "#22c55e",
    "success-foreground": "#020617",
    warning: "#f59e0b",
    "warning-foreground": "#020617",
    info: "#38bdf8",
    "info-foreground": "#020617",
    purple: "#a78bfa",
    border: "rgba(255, 255, 255, 0.1)",
    input: "rgba(255, 255, 255, 0.15)",
    ring: "#3b82f6",
    "chart-1": "#3b82f6",
    "chart-2": "#60a5fa",
    "chart-3": "#22c55e",
    "chart-4": "#f59e0b",
    "chart-5": "#ef4444",
    sidebar: "#0f172a",
    "sidebar-foreground": "#f8fafc",
    "sidebar-primary": "#3b82f6",
    "sidebar-primary-foreground": "#ffffff",
    "sidebar-accent": "#1e293b",
    "sidebar-accent-foreground": "#f8fafc",
    "sidebar-border": "rgba(255, 255, 255, 0.1)",
    "sidebar-ring": "#3b82f6",
  },
  purple: {
    surface: "#faf5ff",
    "surface-dim": "#f3e8ff",
    "surface-bright": "#ffffff",
    "surface-container-lowest": "#ffffff",
    "surface-container-low": "#faf5ff",
    "surface-container": "#f3e8ff",
    "surface-container-high": "#e9d5ff",
    "surface-container-highest": "#d8b4fe",
    "on-surface": "#1e1b4b",
    "on-surface-variant": "#4c1d95",
    "inverse-surface": "#1e1b4b",
    "inverse-on-surface": "#faf5ff",
    outline: "#7c3aed",
    "outline-variant": "rgba(124, 58, 237, 0.25)",
    "surface-tint": "#7c3aed",
    primary: "#7c3aed",
    "on-primary": "#ffffff",
    "primary-container": "#a855f7",
    "on-primary-container": "#ffffff",
    "inverse-primary": "#ddd6fe",
    secondary: "#c084fc",
    "on-secondary": "#ffffff",
    "secondary-container": "#e9d5ff",
    "on-secondary-container": "#4c1d95",
    tertiary: "#943700",
    "on-tertiary": "#ffffff",
    "tertiary-container": "#ffdbcd",
    "on-tertiary-container": "#360f00",
    error: "#ba1a1a",
    "on-error": "#ffffff",
    "error-container": "#ffdad6",
    "on-error-container": "#93000a",
    "primary-fixed": "#ddd6fe",
    "primary-fixed-dim": "#c084fc",
    "on-primary-fixed": "#2e1065",
    "on-primary-fixed-variant": "#6b21a8",
    "secondary-fixed": "#e9d5ff",
    "secondary-fixed-dim": "#d8b4fe",
    "on-secondary-fixed": "#3b0764",
    "on-secondary-fixed-variant": "#7e22ce",
    "tertiary-fixed": "#ffdbcd",
    "tertiary-fixed-dim": "#ffb596",
    "on-tertiary-fixed": "#360f00",
    "on-tertiary-fixed-variant": "#7d2d00",
    background: "#f3e8ff",
    "on-background": "#1e1b4b",
    "surface-variant": "#e9d5ff",
    foreground: "#1e1b4b",
    card: "#ffffff",
    "card-foreground": "#1e1b4b",
    popover: "#ffffff",
    "popover-foreground": "#1e1b4b",
    "primary-hover": "#6d28d9",
    "primary-light": "#ddd6fe",
    muted: "#f3e8ff",
    "muted-foreground": "#6b21a8",
    accent: "#f3e8ff",
    "accent-foreground": "#1e1b4b",
    destructive: "#ba1a1a",
    "destructive-foreground": "#ffffff",
    success: "#22c55e",
    "success-foreground": "#ffffff",
    warning: "#f59e0b",
    "warning-foreground": "#ffffff",
    info: "#7c3aed",
    "info-foreground": "#ffffff",
    purple: "#7c3aed",
    border: "rgba(124, 58, 237, 0.2)",
    input: "rgba(124, 58, 237, 0.2)",
    ring: "#7c3aed",
    "chart-1": "#7c3aed",
    "chart-2": "#c084fc",
    "chart-3": "#22c55e",
    "chart-4": "#f59e0b",
    "chart-5": "#ef4444",
    sidebar: "#ffffff",
    "sidebar-foreground": "#1e1b4b",
    "sidebar-primary": "#7c3aed",
    "sidebar-primary-foreground": "#ffffff",
    "sidebar-accent": "#f3e8ff",
    "sidebar-accent-foreground": "#1e1b4b",
    "sidebar-border": "rgba(124, 58, 237, 0.2)",
    "sidebar-ring": "#7c3aed",
  },
};

const THEME_STORAGE_KEY = "invoisen_theme";

export const themeNames: ThemeName[] = ["light", "dark", "purple"];

export function isThemeName(value: unknown): value is ThemeName {
  return value === "light" || value === "dark" || value === "purple";
}

export function getInitialTheme(): ThemeName {
  if (typeof window === "undefined") return "light";
  const storedTheme = window.localStorage.getItem(THEME_STORAGE_KEY);
  return storedTheme && isThemeName(storedTheme) ? storedTheme : "light";
}

export function setTheme(theme: ThemeName) {
  if (typeof window === "undefined") return;
  window.localStorage.setItem(THEME_STORAGE_KEY, theme);
  applyTheme(theme);
}

export function setCssVariables(theme: ThemeName) {
  if (typeof document === "undefined") return;
  const root = document.documentElement;
  const variables = themes[theme];
  Object.entries(variables).forEach(([name, value]) => {
    root.style.setProperty(`--${name}`, value);
  });
  root.dataset.theme = theme;
}

export function applyTheme(theme: ThemeName) {
  setCssVariables(theme);
}
